// 1. Setup your lists
const INTERESTED_KEYWORDS = ["technology", "coding", "ai", "space"]; 
const IGNORED_KEYWORDS = ["sports", "gossip", "politics"];

async function loadRyanNews() {
    try {
        // Fetch the data generated by your GitHub Action
        const response = await fetch('./news.json');
        const data = await response.json();
        const container = document.querySelector('.challenges-grid');
        
        // Get your personal "Hidden" list from browser memory
        const hiddenArticles = JSON.parse(localStorage.getItem('ryan_ignored_urls')) || [];

        // 2. Filter the news
        const filtered = data.articles.filter(article => {
            // Skip if we manually hid this specific URL before
            if (hiddenArticles.includes(article.url)) return false;

            const content = (article.title + " " + article.description).toLowerCase();
            
            // Hard Ignore: If it matches blocked keywords
            const isBlocked = IGNORED_KEYWORDS.some(word => content.includes(word.toLowerCase()));
            if (isBlocked) return false;

            // Relevance: Only show if it matches interests
            return INTERESTED_KEYWORDS.some(word => content.includes(word.toLowerCase()));
        });

        // 3. Clear placeholders and Render
        container.innerHTML = ''; 

        filtered.forEach(article => {
            const card = document.createElement('div');
            card.className = 'challenge-card';
            
            card.innerHTML = `
                <img src="${article.urlToImage || 'https://via.placeholder.com/400x250'}" 
     alt="news" 
     class="img-card">
<h3>${article.title}</h3>
                <p>${article.description || 'No description provided.'}</p>
                
                <div style="padding: 0 1.5rem 1.5rem; display: flex; justify-content: space-between; align-items: center;">
                    <a href="${article.url}" target="_blank" class="nav-link" style="font-size: 0.8rem;">READ MORE</a>
                    <button onclick="ignoreArticle('${article.url}')" 
                            style="background:none; border:none; color:#ff4d4d; cursor:pointer; font-weight:bold;">
                            ✕ IGNORE
                    </button>
                </div>
            `;
            container.appendChild(card);
        });

    } catch (error) {
        console.error("News feed not ready yet. Ensure news.json exists in your repo.", error);
    }
}

// 4. Persistence Function
function ignoreArticle(url) {
    const hidden = JSON.parse(localStorage.getItem('ryan_ignored_urls')) || [];
    hidden.push(url);
    localStorage.setItem('ryan_ignored_urls', JSON.stringify(hidden));
    
    // Refresh the feed immediately to hide the card
    loadRyanNews();
}

// Initialize
document.addEventListener('DOMContentLoaded', loadRyanNews);
