// 1. User Preferences (Can be moved to a settings menu later)
const INTERESTED_KEYWORDS = ["water", "climate", "sustainability", "environment"];
const IGNORED_KEYWORDS = ["celebrity", "crypto", "stock market", "football"];

async function fetchNews() {
    try {
        // Fetches the news.json file generated by your GitHub Action
        const response = await fetch('./news.json');
        const data = await response.json();
        const newsGrid = document.querySelector('.challenges-grid');

        // 2. Filter Logic
        const filteredArticles = data.articles.filter(article => {
            const content = `${article.title} ${article.description}`.toLowerCase();
            
            // Check if it contains any IGNORED keywords
            const hasIgnored = IGNORED_KEYWORDS.some(word => content.includes(word.toLowerCase()));
            if (hasIgnored) return false;

            // Check if it contains INTERESTED keywords
            const hasInterest = INTERESTED_KEYWORDS.some(word => content.includes(word.toLowerCase()));
            return hasInterest;
        });

        // 3. Clear the static HTML placeholders
        newsGrid.innerHTML = '';

        // 4. Render the filtered news using your CSS classes
        filteredArticles.forEach(article => {
            const card = document.createElement('div');
            card.className = 'challenge-card';
            
            card.innerHTML = `
                <img src="${article.urlToImage || 'https://via.placeholder.com/375x281'}" 
                     alt="${article.title}" 
                     class="challenge-image">
                <h3>${article.title}</h3>
                <p>${article.description || 'No description available for this news item.'}</p>
                <div style="padding: 0 1.5rem 1.5rem; display: flex; justify-content: space-between; align-items: center;">
                    <a href="${article.url}" target="_blank" class="nav-link" style="font-size: 0.8rem; padding: 5px 15px;">READ MORE</a>
                    <button onclick="ignoreArticle(this)" style="background:none; border:none; color:#ff4d4d; cursor:pointer; font-size: 0.8rem; font-weight: bold;">✕ IGNORE</button>
                </div>
            `;
            newsGrid.appendChild(card);
        });
    } catch (error) {
        console.error("Error loading news:", error);
    }
}

// Function to hide card immediately when user clicks ignore
function ignoreArticle(button) {
    const card = button.closest('.challenge-card');
    card.style.opacity = '0';
    setTimeout(() => card.remove(), 300);
}

// Run on page load
window.addEventListener('DOMContentLoaded', fetchNews);
