name: Update News
on:
  schedule:
    - cron: '0 * * * *' # Updates every hour
  workflow_dispatch:     # Allows you to run it manually
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get News
        run: |
          # This fetches the raw data your JS needs
          curl "https://newsapi.org/v2/everything?q=technology&apiKey=${{ secrets.NEWS_API_KEY }}" > news.json
      - name: Commit news
        run: |
          git config --global user.name "Ryan-Bot"
          git config --global user.email "bot@github.com"
          git add news.json
          git commit -m "Update news.json" || exit 0
          git push
